kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "nano-bd-qas"
  label:
    app: "nano-bd"
spec:
  template: 
    metadata:
      labels:
        app: "nano-bd"
    spec:
      containers:
        - name: "nano-bd"
          image: "nano-bd:qas"
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
  replicas: 1
  triggers:
    - type: "ConfigChange" 
    - type: "ImageChange" 
      imageChangeParams:
        automatic: true
        containerNames:
          - "nano-bd"
        from:
          kind: "ImageStreamTag"
          name: "nano-bd:v0.2"
          namespace: vrt-intake
  strategy: 
    type: "Rolling"
  paused: false 
  revisionHistoryLimit: 2 
  minReadySeconds: 0 